export type Difficulty = "beginner" | "intermediate" | "advanced";
export type ExerciseType = "compound" | "isolation" | "cardio";
export type EquipmentType =
  | "none"
  | "dumbbells"
  | "barbell"
  | "bench"
  | "resistance_bands"
  | "pull_up_bar"
  | "cable_machine"
  | "treadmill"
  | "cycle"
  | "kettlebells"
  | "squat_rack"
  | "smith_machine"
  | "dip_bars"
  | "box"
  | "ab_wheel";

export interface ExerciseEntry {
  id: string;
  name: string;
  category: string;
  muscleGroup: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: EquipmentType[];
  difficulty: Difficulty;
  type: ExerciseType;
  sets: number;
  reps: string;
  restSeconds: number;
  notes: string;
}

export const EXERCISE_CATEGORIES = [
  "Chest",
  "Back",
  "Legs",
  "Shoulders",
  "Arms",
  "Core",
  "Glutes",
  "Cardio",
];

export const allExercises: ExerciseEntry[] = [
  // ─── CHEST ───────────────────────────────────────────────────────────────
  { id: "chest_pushup", name: "Push-Up", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 60, notes: "Keep core tight, elbows at 45° to torso" },
  { id: "chest_wide_pushup", name: "Wide-Grip Push-Up", category: "Chest", muscleGroup: "Outer Chest", primaryMuscle: "Outer Pectorals", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 60, notes: "Hands wider than shoulder-width for outer chest emphasis" },
  { id: "chest_diamond_pushup", name: "Diamond Push-Up", category: "Chest", muscleGroup: "Inner Chest", primaryMuscle: "Inner Pectorals", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 60, notes: "Hands form diamond shape, great for inner chest and triceps" },
  { id: "chest_incline_pushup", name: "Incline Push-Up", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps"], equipment: ["bench", "box"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 60, notes: "Feet elevated for lower chest emphasis" },
  { id: "chest_decline_pushup", name: "Decline Push-Up", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts"], equipment: ["bench", "box"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 60, notes: "Hands on floor, feet on bench — targets upper chest" },
  { id: "chest_db_press", name: "Dumbbell Bench Press", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Plant feet firmly, control the descent" },
  { id: "chest_db_fly", name: "Dumbbell Fly", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Front Delts"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 75, notes: "Slight bend in elbows throughout movement" },
  { id: "chest_bb_press", name: "Barbell Bench Press", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["barbell", "bench", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Grip slightly wider than shoulder-width" },
  { id: "chest_incline_db", name: "Incline DB Press", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts", "Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "30-45° incline for upper chest focus" },
  { id: "chest_incline_bb", name: "Incline Barbell Press", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts", "Triceps"], equipment: ["barbell", "bench", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Incline bench at 30-45°, control the bar path" },
  { id: "chest_decline_db", name: "Decline DB Press", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Slight decline targets lower pectorals" },
  { id: "chest_cable_fly", name: "Cable Crossover", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Contract at center, control the arc" },
  { id: "chest_low_cable_fly", name: "Low Cable Fly", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Cables set low, arc up and across for upper chest" },
  { id: "chest_pec_deck", name: "Pec Deck Machine", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Squeeze at peak contraction, controlled return" },
  { id: "chest_db_pullover", name: "Dumbbell Pullover", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Lats", "Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 75, notes: "Keep slight bend in elbows, stretch at the bottom" },
  { id: "chest_band_fly", name: "Resistance Band Fly", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Anchor band at chest height, fly motion" },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  { id: "back_row_db", name: "Dumbbell Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Rhomboids", "Biceps"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Pull elbow back, squeeze at top" },
  { id: "back_pullup", name: "Pull-Up", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: ["pull_up_bar"], difficulty: "intermediate", type: "compound", sets: 3, reps: "5-10", restSeconds: 120, notes: "Full range of motion, dead hang at bottom" },
  { id: "back_chinup", name: "Chin-Up", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Biceps"], equipment: ["pull_up_bar"], difficulty: "intermediate", type: "compound", sets: 3, reps: "5-10", restSeconds: 120, notes: "Supinated grip — palms face you, great bicep involvement" },
  { id: "back_bb_row", name: "Barbell Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Traps", "Rhomboids", "Biceps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 90, notes: "Hinge at hips, pull to lower chest" },
  { id: "back_pendlay_row", name: "Pendlay Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Traps", "Rhomboids"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 4, reps: "5-8", restSeconds: 120, notes: "Bar starts on floor each rep, explosive row to chest" },
  { id: "back_cable_row", name: "Seated Cable Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Keep chest up, drive elbows back" },
  { id: "back_lat_pulldown", name: "Lat Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-12", restSeconds: 75, notes: "Pull to upper chest, lean back slightly" },
  { id: "back_wide_pulldown", name: "Wide-Grip Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Rear Delts"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Extra wide grip emphasises lat width" },
  { id: "back_straight_arm_pulldown", name: "Straight-Arm Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Triceps"], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Arms straight, hinge at shoulder only" },
  { id: "back_deadlift", name: "Romanian Deadlift", category: "Back", muscleGroup: "Back/Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10", restSeconds: 120, notes: "Hinge at hips, soft knees, bar close to legs" },
  { id: "back_deadlift_conv", name: "Conventional Deadlift", category: "Back", muscleGroup: "Back", primaryMuscle: "Lower Back", secondaryMuscles: ["Hamstrings", "Glutes", "Traps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "4-6", restSeconds: 180, notes: "Hip-width stance, bar over mid-foot, neutral spine throughout" },
  { id: "back_good_morning", name: "Good Morning", category: "Back", muscleGroup: "Lower Back", primaryMuscle: "Lower Back", secondaryMuscles: ["Hamstrings", "Glutes"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 3, reps: "8-10", restSeconds: 90, notes: "Bar on upper traps, hinge at hips with slight knee bend" },
  { id: "back_tbar_row", name: "T-Bar Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Rhomboids", "Traps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Chest pad or no pad, drive elbows back and high" },
  { id: "back_hyper_ext", name: "Hyperextension", category: "Back", muscleGroup: "Lower Back", primaryMuscle: "Erector Spinae", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["bench"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Don't hyperextend at the top, controlled throughout" },
  { id: "back_inverted_row", name: "Inverted Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["pull_up_bar"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 75, notes: "Body under bar, pull chest to bar — great bodyweight row" },
  { id: "back_band_row", name: "Resistance Band Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["resistance_bands"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Anchor band low, seated or standing, drive elbows back" },

  // ─── LEGS ─────────────────────────────────────────────────────────────────
  { id: "legs_squat", name: "Bodyweight Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Chest up, knees track over toes" },
  { id: "legs_jump_squat", name: "Jump Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 60, notes: "Explode upward, land softly with bent knees" },
  { id: "legs_db_squat", name: "Goblet Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["dumbbells", "kettlebells"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-12", restSeconds: 90, notes: "Hold dumbbell at chest, upright torso" },
  { id: "legs_bb_squat", name: "Back Squat", category: "Legs", muscleGroup: "Quads/Glutes", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], equipment: ["barbell", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Bar on upper traps, break parallel" },
  { id: "legs_front_squat", name: "Front Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["barbell", "squat_rack"], difficulty: "advanced", type: "compound", sets: 4, reps: "5-8", restSeconds: 120, notes: "Bar on front delts, upright torso, deep squat" },
  { id: "legs_sumo_squat", name: "Sumo Squat", category: "Legs", muscleGroup: "Inner Thighs", primaryMuscle: "Adductors", secondaryMuscles: ["Glutes", "Quads"], equipment: ["dumbbells", "kettlebells"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 75, notes: "Wide stance, toes out, weight between legs" },
  { id: "legs_lunge", name: "Walking Lunge", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Long stride, front knee over ankle" },
  { id: "legs_reverse_lunge", name: "Reverse Lunge", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Step back, lower back knee toward floor" },
  { id: "legs_curtsy_lunge", name: "Curtsy Lunge", category: "Legs", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Adductors"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Cross back leg behind and to the outside" },
  { id: "legs_rdl", name: "Romanian Deadlift (DB)", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 90, notes: "Hinge at hips, feel hamstring stretch" },
  { id: "legs_nordics", name: "Nordic Curl", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: [], equipment: ["bench"], difficulty: "advanced", type: "isolation", sets: 3, reps: "5-8", restSeconds: 90, notes: "Feet anchored, lower slowly using hamstrings" },
  { id: "legs_leg_curl", name: "Leg Curl", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Controlled negative, full range of motion" },
  { id: "legs_leg_ext", name: "Leg Extension", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Squeeze quad at top, control the descent" },
  { id: "legs_calf", name: "Calf Raise", category: "Legs", muscleGroup: "Calves", primaryMuscle: "Gastrocnemius", secondaryMuscles: ["Soleus"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 4, reps: "15-20", restSeconds: 45, notes: "Full range, pause at top" },
  { id: "legs_seated_calf", name: "Seated Calf Raise", category: "Legs", muscleGroup: "Calves", primaryMuscle: "Soleus", secondaryMuscles: ["Gastrocnemius"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Seated position isolates the soleus" },
  { id: "legs_leg_press", name: "Leg Press", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-15", restSeconds: 90, notes: "Feet shoulder-width, don't lock out knees" },
  { id: "legs_hack_squat", name: "Hack Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["cable_machine"], difficulty: "intermediate", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Low bar position on shoulders, deep squat" },
  { id: "legs_step_up", name: "Step-Up", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["box", "bench"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 60, notes: "Drive through heel, controlled descent" },
  { id: "legs_sissy_squat", name: "Sissy Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: [], equipment: ["none"], difficulty: "advanced", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lean back, knees forward over toes" },
  { id: "legs_split_squat", name: "Bulgarian Split Squat", category: "Legs", muscleGroup: "Quads/Glutes", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10/leg", restSeconds: 90, notes: "Rear foot on bench, drive through front heel" },

  // ─── SHOULDERS ────────────────────────────────────────────────────────────
  { id: "sh_lateral", name: "Lateral Raise", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Slight bend in elbows, lead with elbows" },
  { id: "sh_cable_lateral", name: "Cable Lateral Raise", category: "Shoulders", muscleGroup: "Lateral Delts", primaryMuscle: "Lateral Delts", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Constant tension throughout the range" },
  { id: "sh_ohp_db", name: "DB Overhead Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps", "Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Core tight, press straight overhead" },
  { id: "sh_ohp_bb", name: "Barbell OHP", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps", "Traps"], equipment: ["barbell", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Bar starts at upper chest, press overhead" },
  { id: "sh_arnold_press", name: "Arnold Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 90, notes: "Rotate palms out as you press — hits all three delt heads" },
  { id: "sh_front_raise", name: "Front Raise", category: "Shoulders", muscleGroup: "Front Delts", primaryMuscle: "Front Delts", secondaryMuscles: [], equipment: ["dumbbells", "barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Controlled movement, don't swing" },
  { id: "sh_face_pull", name: "Face Pull", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rotator Cuff", "Traps"], equipment: ["cable_machine", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Pull to forehead level, external rotation" },
  { id: "sh_reverse_fly", name: "Reverse Fly", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Hinge forward, fly out to the sides" },
  { id: "sh_upright_row", name: "Upright Row", category: "Shoulders", muscleGroup: "Shoulders/Traps", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Traps", "Biceps"], equipment: ["barbell", "dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Bar close to body, lead with elbows up to chin level" },
  { id: "sh_shrug", name: "Barbell Shrug", category: "Shoulders", muscleGroup: "Traps", primaryMuscle: "Traps", secondaryMuscles: [], equipment: ["barbell", "dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Shrug straight up, hold at top for 1s" },
  { id: "sh_band_pull_apart", name: "Band Pull-Apart", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rhomboids"], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20-25", restSeconds: 45, notes: "Arms straight, pull band apart to chest width" },
  { id: "sh_pike_pushup", name: "Pike Push-Up", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 75, notes: "Hips high in pike position, lower head toward floor" },

  // ─── ARMS ─────────────────────────────────────────────────────────────────
  { id: "arm_curl_db", name: "Dumbbell Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Supinate at top, control the descent" },
  { id: "arm_curl_bb", name: "Barbell Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], equipment: ["barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Full range, don't cheat with momentum" },
  { id: "arm_hammer_curl", name: "Hammer Curl", category: "Arms", muscleGroup: "Biceps/Brachialis", primaryMuscle: "Brachialis", secondaryMuscles: ["Biceps", "Brachioradialis"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Neutral grip, controlled movement" },
  { id: "arm_incline_curl", name: "Incline DB Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps Long Head", secondaryMuscles: ["Brachialis"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Incline bench stretches bicep at bottom for full ROM" },
  { id: "arm_conc_curl", name: "Concentration Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Elbow on inner knee, strict curl for peak contraction" },
  { id: "arm_cable_curl", name: "Cable Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Constant tension, don't let elbows flare" },
  { id: "arm_preacher_curl", name: "Preacher Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps Short Head", secondaryMuscles: [], equipment: ["barbell", "cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Arm on pad, full stretch at bottom" },
  { id: "arm_tricep_ext", name: "Overhead Tricep Extension", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Keep elbows tucked, extend fully" },
  { id: "arm_tricep_pushdown", name: "Cable Pushdown", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Lateral Head", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Elbows fixed to sides, full extension" },
  { id: "arm_dips", name: "Tricep Dips", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Front Delts", "Chest"], equipment: ["dip_bars", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lean slightly forward, elbows behind you" },
  { id: "arm_skull_crusher", name: "Skull Crusher", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["barbell", "dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lower bar to forehead, keep elbows fixed" },
  { id: "arm_close_grip_press", name: "Close-Grip Bench Press", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], equipment: ["barbell", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Shoulder-width grip, elbows tucked in" },
  { id: "arm_overhead_cable_ext", name: "Overhead Cable Extension", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Face away from cable, extend arms overhead" },
  { id: "arm_diamond_pushup", name: "Diamond Push-Up", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-15", restSeconds: 60, notes: "Diamond hand position, elbows flare out slightly" },
  { id: "arm_kickback", name: "Tricep Kickback", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Upper arm parallel to floor, extend fully at back" },

  // ─── CORE ─────────────────────────────────────────────────────────────────
  { id: "core_plank", name: "Plank", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abdominis", secondaryMuscles: ["Obliques", "Glutes"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "30-60s", restSeconds: 60, notes: "Neutral spine, squeeze everything" },
  { id: "core_side_plank", name: "Side Plank", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Core"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20-40s/side", restSeconds: 60, notes: "Body in straight line, stack feet" },
  { id: "core_crunch", name: "Crunch", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abdominis", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Controlled, don't pull on neck" },
  { id: "core_cable_crunch", name: "Cable Crunch", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abdominis", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Kneel, flex spine — not just hip flexors" },
  { id: "core_bicycle", name: "Bicycle Crunch", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Rectus Abdominis"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/side", restSeconds: 45, notes: "Slow and controlled rotation" },
  { id: "core_dead_bug", name: "Dead Bug", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abdominis", secondaryMuscles: ["Obliques"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10/side", restSeconds: 60, notes: "Keep lower back pressed to floor" },
  { id: "core_leg_raise", name: "Leg Raise", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Rectus Abdominis", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Lower back stays on floor" },
  { id: "core_hanging_leg_raise", name: "Hanging Leg Raise", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Rectus Abdominis", secondaryMuscles: ["Hip Flexors"], equipment: ["pull_up_bar"], difficulty: "advanced", type: "isolation", sets: 3, reps: "10-15", restSeconds: 75, notes: "Don't swing, curl hips up at top" },
  { id: "core_ab_wheel", name: "Ab Wheel Rollout", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abdominis", secondaryMuscles: ["Lats", "Obliques"], equipment: ["ab_wheel"], difficulty: "advanced", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Hips forward, fully extend and retract" },
  { id: "core_russian_twist", name: "Russian Twist", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Rectus Abdominis"], equipment: ["none", "dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/side", restSeconds: 45, notes: "Feet off floor for more challenge" },
  { id: "core_mountain_climber", name: "Mountain Climbers", category: "Core", muscleGroup: "Core/Cardio", primaryMuscle: "Core", secondaryMuscles: ["Hip Flexors", "Shoulders"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "20s", restSeconds: 30, notes: "Keep hips low, fast pace" },
  { id: "core_hollow_hold", name: "Hollow Body Hold", category: "Core", muscleGroup: "Core", primaryMuscle: "Rectus Abdominis", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "20-40s", restSeconds: 60, notes: "Lower back flat, arms and legs extended low" },
  { id: "core_v_up", name: "V-Up", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abdominis", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Lift legs and torso simultaneously, meet in the middle" },
  { id: "core_windshield_wiper", name: "Windshield Wiper", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Lower Abs"], equipment: ["none"], difficulty: "advanced", type: "isolation", sets: 3, reps: "10/side", restSeconds: 75, notes: "Legs together, rotate side to side controlled" },

  // ─── GLUTES ───────────────────────────────────────────────────────────────
  { id: "glute_hip_thrust", name: "Barbell Hip Thrust", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings"], equipment: ["barbell", "bench"], difficulty: "intermediate", type: "isolation", sets: 4, reps: "10-15", restSeconds: 90, notes: "Shoulders on bench, squeeze glutes at top" },
  { id: "glute_db_hip_thrust", name: "Dumbbell Hip Thrust", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 75, notes: "DB on hips, drive through heels" },
  { id: "glute_bridge", name: "Glute Bridge", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Feet flat, squeeze glutes at top" },
  { id: "glute_single_bridge", name: "Single-Leg Glute Bridge", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12/leg", restSeconds: 60, notes: "One leg raised, drive hip up with standing leg" },
  { id: "glute_kickback", name: "Cable Glute Kickback", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15/leg", restSeconds: 60, notes: "Slight forward lean, kick back squeezing glute" },
  { id: "glute_band_kickback", name: "Banded Glute Kickback", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 60, notes: "On all fours, kick leg back and up" },
  { id: "glute_fire_hydrant", name: "Fire Hydrant", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Medius", secondaryMuscles: [], equipment: ["none", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "On all fours, lift knee out to side" },
  { id: "glute_clamshell", name: "Clamshell", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Medius", secondaryMuscles: [], equipment: ["none", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "Feet together, open top knee like a clamshell" },
  { id: "glute_side_lying_abduction", name: "Side-Lying Abduction", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Medius", secondaryMuscles: [], equipment: ["none", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "Lift top leg in a controlled arc" },
  { id: "glute_rdl_single", name: "Single-Leg RDL", category: "Glutes", muscleGroup: "Glutes/Hamstrings", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings"], equipment: ["dumbbells", "none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10/leg", restSeconds: 75, notes: "Hinge at hip, back leg floats back, feel stretch" },
  { id: "glute_sumo_deadlift", name: "Sumo Deadlift", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Adductors", "Hamstrings"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Wide stance, toes out, hips close to bar" },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  { id: "cardio_jumping_jacks", name: "Jumping Jacks", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "30s", restSeconds: 30, notes: "Warm-up or HIIT finisher" },
  { id: "cardio_burpee", name: "Burpee", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "10", restSeconds: 60, notes: "Land softly from jump" },
  { id: "cardio_high_knees", name: "High Knees", category: "Cardio", muscleGroup: "Cardio", primaryMuscle: "Hip Flexors", secondaryMuscles: ["Quads", "Core"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "30s", restSeconds: 30, notes: "Drive knees up to hip height, pump arms" },
  { id: "cardio_box_jump", name: "Box Jump", category: "Cardio", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["box"], difficulty: "intermediate", type: "cardio", sets: 4, reps: "5-8", restSeconds: 90, notes: "Explode up, land softly, step down" },
  { id: "cardio_jump_rope", name: "Jump Rope", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Calves", secondaryMuscles: ["Shoulders", "Core"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "1 min", restSeconds: 30, notes: "Land on balls of feet, small jumps" },
  { id: "cardio_treadmill", name: "Treadmill Run", category: "Cardio", muscleGroup: "Cardio", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["treadmill"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "Zone 2 cardio at conversational pace" },
  { id: "cardio_cycle", name: "Cycling", category: "Cardio", muscleGroup: "Cardio", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["cycle"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "Moderate resistance, steady cadence" },
  { id: "cardio_row_machine", name: "Rowing Machine", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "cardio", sets: 1, reps: "15-20 min", restSeconds: 0, notes: "Drive with legs, then lean back and pull" },
  { id: "cardio_sprint", name: "Sprint Interval", category: "Cardio", muscleGroup: "Cardio", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["treadmill", "none"], difficulty: "intermediate", type: "cardio", sets: 6, reps: "30s on / 90s off", restSeconds: 90, notes: "Max effort sprints, full recovery between" },
  { id: "cardio_stair_climb", name: "Stair Climber", category: "Cardio", muscleGroup: "Cardio", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["cable_machine"], difficulty: "beginner", type: "cardio", sets: 1, reps: "15-20 min", restSeconds: 0, notes: "Steady pace, full foot on each step" },
  { id: "cardio_bear_crawl", name: "Bear Crawl", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Core", "Quads"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "20m", restSeconds: 60, notes: "Knees hovering, crawl forward and backward" },
  { id: "cardio_battle_ropes", name: "Battle Ropes", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Core", "Back"], equipment: ["resistance_bands"], difficulty: "intermediate", type: "cardio", sets: 4, reps: "30s", restSeconds: 60, notes: "Alternate arms, keep slight knee bend" },
  { id: "cardio_skater_jump", name: "Skater Jump", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Core"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "12/side", restSeconds: 45, notes: "Lateral bounds, land on one foot softly" },
  { id: "cardio_lunge_jump", name: "Jump Lunge", category: "Cardio", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "10/leg", restSeconds: 60, notes: "Switch legs in mid-air, land softly" },

  // ─── ADDITIONAL CHEST ────────────────────────────────────────────────────
  { id: "chest_pushup_plus", name: "Push-Up Plus (Serratus)", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Serratus Anterior", secondaryMuscles: ["Pectorals"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 45, notes: "At top of push-up, push forward to protract shoulder blades" },
  { id: "chest_dip", name: "Chest Dip", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["dip_bars"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Lean forward slightly to target chest over triceps" },

  // ─── ADDITIONAL BACK ─────────────────────────────────────────────────────
  { id: "back_shrug_db", name: "Dumbbell Shrug", category: "Back", muscleGroup: "Traps", primaryMuscle: "Traps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 4, reps: "12-15", restSeconds: 60, notes: "Straight up shrug, hold at top for 1s" },
  { id: "back_face_pull_band", name: "Band Face Pull", category: "Back", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rotator Cuff", "Rhomboids"], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20", restSeconds: 45, notes: "Anchor band at face height, pull to ears" },
  { id: "back_meadows_row", name: "Meadows Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Teres Major", "Biceps"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 3, reps: "8-10", restSeconds: 90, notes: "Barbell in corner, landmine position, pull to hip" },
  { id: "back_cable_pullover", name: "Cable Pullover", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Chest", "Triceps"], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Cable high, arms straight, sweep down to hips" },

  // ─── ADDITIONAL LEGS ─────────────────────────────────────────────────────
  { id: "legs_pistol_squat", name: "Pistol Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["none"], difficulty: "advanced", type: "compound", sets: 3, reps: "5-8/leg", restSeconds: 90, notes: "Single-leg squat to parallel, maintain balance" },
  { id: "legs_wall_sit", name: "Wall Sit", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "30-60s", restSeconds: 60, notes: "90° at knees and hips, back flat on wall" },
  { id: "legs_band_squat", name: "Banded Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Adductors"], equipment: ["resistance_bands"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Band around knees, push outward as you squat" },
  { id: "legs_db_deadlift", name: "Dumbbell Deadlift", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: ["dumbbells"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 90, notes: "Flat back, hinge at hips, drive through heels" },

  // ─── ADDITIONAL SHOULDERS ─────────────────────────────────────────────────
  { id: "sh_plate_raise", name: "Plate Front Raise", category: "Shoulders", muscleGroup: "Front Delts", primaryMuscle: "Front Delts", secondaryMuscles: [], equipment: ["barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Hold weight plate, raise to shoulder height" },
  { id: "sh_seated_ohp", name: "Seated DB Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Back supported, press from ear level overhead" },

  // ─── ADDITIONAL ARMS ──────────────────────────────────────────────────────
  { id: "arm_zottman_curl", name: "Zottman Curl", category: "Arms", muscleGroup: "Biceps/Forearms", primaryMuscle: "Biceps", secondaryMuscles: ["Brachioradialis", "Brachialis"], equipment: ["dumbbells"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Curl up supinated, pronate at top, lower pronated" },
  { id: "arm_cross_curl", name: "Cross-Body Hammer Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Brachialis", secondaryMuscles: ["Biceps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Curl across the body toward opposite shoulder" },
  { id: "arm_band_curl", name: "Resistance Band Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Stand on band, curl both arms together" },
  { id: "arm_band_tricep_ext", name: "Band Tricep Extension", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Anchor band overhead, extend arms to full lockout" },

  // ─── ADDITIONAL CORE ──────────────────────────────────────────────────────
  { id: "core_toe_touch", name: "Toe Touch", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abdominis", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Legs vertical, crunch up to touch toes" },
  { id: "core_pallof_press", name: "Pallof Press", category: "Core", muscleGroup: "Core", primaryMuscle: "Obliques", secondaryMuscles: ["Transverse Abdominis"], equipment: ["cable_machine", "resistance_bands"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12/side", restSeconds: 60, notes: "Anti-rotation — resist cable pulling you sideways" },
  { id: "core_wood_chop", name: "Cable Wood Chop", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Core", "Shoulders"], equipment: ["cable_machine", "resistance_bands"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12/side", restSeconds: 60, notes: "Rotate from high to low in a diagonal pattern" },
  { id: "core_dragon_flag", name: "Dragon Flag", category: "Core", muscleGroup: "Core", primaryMuscle: "Rectus Abdominis", secondaryMuscles: ["Lower Back", "Glutes"], equipment: ["bench"], difficulty: "advanced", type: "isolation", sets: 3, reps: "5-8", restSeconds: 90, notes: "Hold bench behind head, lower and raise full body" },

  // ─── ADDITIONAL GLUTES ────────────────────────────────────────────────────
  { id: "glute_cable_pull_through", name: "Cable Pull-Through", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Hamstrings", "Lower Back"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 75, notes: "Cable low, hinge at hips, squeeze glutes at top" },
  { id: "glute_donkey_kick", name: "Donkey Kick", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: [], equipment: ["none", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "On all fours, kick heel toward ceiling" },
  { id: "glute_frog_pump", name: "Frog Pump", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Adductors"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20-30", restSeconds: 45, notes: "Feet together, knees out, pump hips upward" },
  { id: "glute_hip_abduction", name: "Hip Abduction Machine", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Medius", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Push knees outward against pads, controlled return" },

  // ─── ADDITIONAL COMPOUND / FULL BODY ──────────────────────────────────────
  { id: "full_clean_press", name: "Dumbbell Clean & Press", category: "Shoulders", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Traps", "Quads", "Core"], equipment: ["dumbbells"], difficulty: "advanced", type: "compound", sets: 4, reps: "6-8", restSeconds: 90, notes: "Power clean the dumbbells up, then press overhead" },
  { id: "full_thruster", name: "Thruster", category: "Shoulders", muscleGroup: "Full Body", primaryMuscle: "Quads", secondaryMuscles: ["Shoulders", "Glutes", "Core"], equipment: ["barbell", "dumbbells"], difficulty: "advanced", type: "compound", sets: 4, reps: "6-8", restSeconds: 120, notes: "Front squat straight into overhead press — no pause" },
  { id: "full_kb_swing", name: "Kettlebell Swing", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Core", "Shoulders"], equipment: ["kettlebells"], difficulty: "intermediate", type: "compound", sets: 4, reps: "15-20", restSeconds: 60, notes: "Hinge hard at hip, power from glutes — not a squat" },
  { id: "full_kb_goblet", name: "Kettlebell Goblet Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["kettlebells"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 75, notes: "Hold bell at chest, deep squat with upright torso" },
  { id: "full_lunge_press", name: "Lunge with Shoulder Press", category: "Legs", muscleGroup: "Full Body", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Shoulders"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Lunge forward while pressing dumbbells overhead simultaneously" },
  { id: "full_band_good_morning", name: "Banded Good Morning", category: "Back", muscleGroup: "Lower Back", primaryMuscle: "Erector Spinae", secondaryMuscles: ["Hamstrings", "Glutes"], equipment: ["resistance_bands"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Band over shoulders, hinge forward with flat back" },
  { id: "full_db_snatch", name: "Dumbbell Snatch", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Glutes", "Traps", "Core"], equipment: ["dumbbells"], difficulty: "advanced", type: "compound", sets: 4, reps: "5/arm", restSeconds: 90, notes: "Single arm — pull from floor to overhead in one explosive motion" },
  { id: "full_sumo_hip_thrust", name: "Sumo Stance Hip Thrust", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Gluteus Maximus", secondaryMuscles: ["Adductors", "Hamstrings"], equipment: ["barbell", "bench"], difficulty: "intermediate", type: "isolation", sets: 4, reps: "10-15", restSeconds: 90, notes: "Wide foot placement, toes out — emphasises adductors and glutes" },
  { id: "full_renegade_row", name: "Renegade Row", category: "Back", muscleGroup: "Back/Core", primaryMuscle: "Lats", secondaryMuscles: ["Core", "Shoulders"], equipment: ["dumbbells"], difficulty: "advanced", type: "compound", sets: 3, reps: "8/arm", restSeconds: 90, notes: "Plank with dumbbells, row one arm at a time" },
  { id: "full_bear_row", name: "Bear Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Core"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/arm", restSeconds: 75, notes: "All-fours position, row dumbbell to hip" },
  { id: "arm_reverse_curl", name: "Reverse Curl", category: "Arms", muscleGroup: "Forearms", primaryMuscle: "Brachioradialis", secondaryMuscles: ["Biceps"], equipment: ["barbell", "dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Overhand grip, curl up — great for forearm development" },
  { id: "arm_wrist_curl", name: "Wrist Curl", category: "Arms", muscleGroup: "Forearms", primaryMuscle: "Forearm Flexors", secondaryMuscles: [], equipment: ["barbell", "dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Forearms on bench, wrists hanging, curl up" },
];

export function getExercisesByCategory(category: string): ExerciseEntry[] {
  return allExercises.filter((e) => e.category === category);
}

export function searchExercises(query: string): ExerciseEntry[] {
  const q = query.toLowerCase();
  return allExercises.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.muscleGroup.toLowerCase().includes(q) ||
      e.primaryMuscle.toLowerCase().includes(q) ||
      e.category.toLowerCase().includes(q)
  );
}

export function getExercisesByEquipment(available: string[]): ExerciseEntry[] {
  return allExercises.filter((e) =>
    e.equipment.some((eq) => eq === "none" || available.includes(eq))
  );
}

export function getExerciseById(id: string): ExerciseEntry | undefined {
  return allExercises.find((e) => e.id === id);
}
