export type Difficulty = "beginner" | "intermediate" | "advanced";
export type ExerciseType = "compound" | "isolation" | "cardio";
export type EquipmentType =
  | "none"
  | "dumbbells"
  | "barbell"
  | "bench"
  | "resistance_bands"
  | "pull_up_bar"
  | "cable_machine"
  | "treadmill"
  | "cycle"
  | "kettlebells"
  | "squat_rack"
  | "smith_machine"
  | "dip_bars"
  | "box"
  | "ab_wheel";

export interface ExerciseEntry {
  id: string;
  name: string;
  category: string;
  muscleGroup: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: EquipmentType[];
  difficulty: Difficulty;
  type: ExerciseType;
  sets: number;
  reps: string;
  restSeconds: number;
  notes: string;
}

export const EXERCISE_CATEGORIES = [
  "Chest",
  "Back",
  "Legs",
  "Shoulders",
  "Arms",
  "Core",
  "Glutes",
  "Cardio",
];

export const allExercises: ExerciseEntry[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // CHEST (~22 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "chest_pushup", name: "Push-Up", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 60, notes: "Keep core tight, elbows at 45° to torso" },
  { id: "chest_wide_pushup", name: "Wide-Grip Push-Up", category: "Chest", muscleGroup: "Outer Chest", primaryMuscle: "Outer Pectorals", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 60, notes: "Hands wider than shoulder-width for outer chest emphasis" },
  { id: "chest_diamond_pushup", name: "Diamond Push-Up", category: "Chest", muscleGroup: "Inner Chest", primaryMuscle: "Inner Pectorals", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 60, notes: "Hands form diamond shape, great for inner chest and triceps" },
  { id: "chest_incline_pushup", name: "Incline Push-Up", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps"], equipment: ["bench", "box"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 60, notes: "Feet elevated for lower chest emphasis" },
  { id: "chest_decline_pushup", name: "Decline Push-Up", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts"], equipment: ["bench", "box"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 60, notes: "Hands on floor, feet on bench — targets upper chest" },
  { id: "chest_clap_pushup", name: "Clap Push-Up", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["none"], difficulty: "advanced", type: "compound", sets: 3, reps: "6-10", restSeconds: 75, notes: "Explosive push, clap at top, land softly" },
  { id: "chest_db_press", name: "Dumbbell Bench Press", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Plant feet firmly, control the descent" },
  { id: "chest_db_fly", name: "Dumbbell Fly", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Front Delts"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 75, notes: "Slight bend in elbows throughout movement" },
  { id: "chest_bb_press", name: "Barbell Bench Press", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["barbell", "bench", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Grip slightly wider than shoulder-width" },
  { id: "chest_incline_db", name: "Incline DB Press", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts", "Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "30-45° incline for upper chest focus" },
  { id: "chest_incline_bb", name: "Incline Barbell Press", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts", "Triceps"], equipment: ["barbell", "bench", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Incline bench at 30-45°, control the bar path" },
  { id: "chest_decline_db", name: "Decline DB Press", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Slight decline targets lower pectorals" },
  { id: "chest_cable_fly", name: "Cable Crossover", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Contract at center, control the arc" },
  { id: "chest_low_cable_fly", name: "Low Cable Fly", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Cables set low, arc up and across for upper chest" },
  { id: "chest_pec_deck", name: "Pec Deck Machine", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Squeeze at peak contraction, controlled return" },
  { id: "chest_db_pullover", name: "Dumbbell Pullover", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Lats", "Triceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 75, notes: "Keep slight bend in elbows, stretch at the bottom" },
  { id: "chest_band_fly", name: "Resistance Band Fly", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Anchor band at chest height, fly motion" },
  { id: "chest_smith_press", name: "Smith Machine Bench Press", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["smith_machine", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Guided bar path, focus on mind-muscle connection" },
  { id: "chest_svend_press", name: "Svend Press", category: "Chest", muscleGroup: "Inner Chest", primaryMuscle: "Pectorals", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Press plates together in front of chest and extend" },
  { id: "chest_floor_press", name: "Floor Press (DB)", category: "Chest", muscleGroup: "Chest", primaryMuscle: "Pectorals", secondaryMuscles: ["Triceps"], equipment: ["dumbbells"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Lie on floor, limited ROM protects shoulders" },
  { id: "chest_dips", name: "Chest Dips", category: "Chest", muscleGroup: "Lower Chest", primaryMuscle: "Lower Pectorals", secondaryMuscles: ["Triceps", "Front Delts"], equipment: ["dip_bars"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Lean forward for chest emphasis, go deep" },
  { id: "chest_landmine_press", name: "Landmine Press", category: "Chest", muscleGroup: "Upper Chest", primaryMuscle: "Upper Pectorals", secondaryMuscles: ["Front Delts", "Triceps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Bar anchored in corner, press at upward angle" },

  // ═══════════════════════════════════════════════════════════════════════════
  // BACK (~22 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "back_row_db", name: "Dumbbell Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Rhomboids", "Biceps"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Pull elbow back, squeeze at top" },
  { id: "back_pullup", name: "Pull-Up", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: ["pull_up_bar"], difficulty: "intermediate", type: "compound", sets: 3, reps: "5-10", restSeconds: 120, notes: "Full range of motion, dead hang at bottom" },
  { id: "back_chinup", name: "Chin-Up", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Biceps"], equipment: ["pull_up_bar"], difficulty: "intermediate", type: "compound", sets: 3, reps: "5-10", restSeconds: 120, notes: "Supinated grip — palms face you, great bicep involvement" },
  { id: "back_bb_row", name: "Barbell Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Traps", "Rhomboids", "Biceps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 90, notes: "Hinge at hips, pull to lower chest" },
  { id: "back_pendlay_row", name: "Pendlay Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Traps", "Rhomboids"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 4, reps: "5-8", restSeconds: 120, notes: "Bar starts on floor each rep, explosive row to chest" },
  { id: "back_cable_row", name: "Seated Cable Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Keep chest up, drive elbows back" },
  { id: "back_lat_pulldown", name: "Lat Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Biceps", "Rear Delts"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-12", restSeconds: 75, notes: "Pull to upper chest, lean back slightly" },
  { id: "back_wide_pulldown", name: "Wide-Grip Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Rear Delts"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Extra wide grip emphasises lat width" },
  { id: "back_close_grip_pulldown", name: "Close-Grip Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Biceps"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "V-bar attachment, squeeze shoulder blades" },
  { id: "back_straight_arm_pulldown", name: "Straight-Arm Pulldown", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Triceps"], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Arms straight, hinge at shoulder only" },
  { id: "back_deadlift", name: "Romanian Deadlift", category: "Back", muscleGroup: "Back/Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10", restSeconds: 120, notes: "Hinge at hips, soft knees, bar close to legs" },
  { id: "back_deadlift_conv", name: "Conventional Deadlift", category: "Back", muscleGroup: "Back", primaryMuscle: "Lower Back", secondaryMuscles: ["Hamstrings", "Glutes", "Traps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "4-6", restSeconds: 180, notes: "Hip-width stance, bar over mid-foot, neutral spine throughout" },
  { id: "back_sumo_deadlift", name: "Sumo Deadlift", category: "Back", muscleGroup: "Back", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Hamstrings", "Lower Back"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "4-6", restSeconds: 180, notes: "Wide stance, toes out, chest tall, push the floor" },
  { id: "back_good_morning", name: "Good Morning", category: "Back", muscleGroup: "Lower Back", primaryMuscle: "Lower Back", secondaryMuscles: ["Hamstrings", "Glutes"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 3, reps: "8-10", restSeconds: 90, notes: "Bar on upper traps, hinge at hips with slight knee bend" },
  { id: "back_tbar_row", name: "T-Bar Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Rhomboids", "Traps"], equipment: ["barbell"], difficulty: "intermediate", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Chest pad or no pad, drive elbows back and high" },
  { id: "back_hyper_ext", name: "Hyperextension", category: "Back", muscleGroup: "Lower Back", primaryMuscle: "Erector Spinae", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["bench"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Don't hyperextend at the top, controlled throughout" },
  { id: "back_inverted_row", name: "Inverted Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["pull_up_bar"], difficulty: "beginner", type: "compound", sets: 3, reps: "10-15", restSeconds: 75, notes: "Body under bar, pull chest to bar — great bodyweight row" },
  { id: "back_band_row", name: "Resistance Band Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Rhomboids", secondaryMuscles: ["Lats", "Biceps"], equipment: ["resistance_bands"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Anchor band low, seated or standing, drive elbows back" },
  { id: "back_meadows_row", name: "Meadows Row", category: "Back", muscleGroup: "Lats", primaryMuscle: "Lats", secondaryMuscles: ["Rear Delts", "Biceps"], equipment: ["barbell"], difficulty: "advanced", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Staggered stance, one-arm landmine row for lat stretch" },
  { id: "back_seal_row", name: "Seal Row", category: "Back", muscleGroup: "Back", primaryMuscle: "Lats", secondaryMuscles: ["Rhomboids", "Biceps"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Lie chest-down on bench, row both DBs — no cheating" },
  { id: "back_face_pull_rear", name: "Cable Face Pull (rear delt)", category: "Back", muscleGroup: "Upper Back", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps"], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "External rotation at top, elbows high" },
  { id: "back_kb_swing", name: "Kettlebell Swing", category: "Back", muscleGroup: "Posterior Chain", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Lower Back", "Core"], equipment: ["kettlebells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "15-20", restSeconds: 75, notes: "Hip hinge, explosive hip drive, arms are pendulums" },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEGS (~26 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "legs_squat", name: "Bodyweight Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Chest up, knees track over toes" },
  { id: "legs_jump_squat", name: "Jump Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 60, notes: "Explode upward, land softly with bent knees" },
  { id: "legs_db_squat", name: "Goblet Squat", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["dumbbells", "kettlebells"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-12", restSeconds: 90, notes: "Hold dumbbell at chest, upright torso" },
  { id: "legs_bb_squat", name: "Back Squat", category: "Legs", muscleGroup: "Quads/Glutes", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Core"], equipment: ["barbell", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Bar on upper traps, break parallel" },
  { id: "legs_front_squat", name: "Front Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["barbell", "squat_rack"], difficulty: "advanced", type: "compound", sets: 4, reps: "5-8", restSeconds: 120, notes: "Bar on front delts, upright torso, deep squat" },
  { id: "legs_sumo_squat", name: "Sumo Squat", category: "Legs", muscleGroup: "Inner Thighs", primaryMuscle: "Adductors", secondaryMuscles: ["Glutes", "Quads"], equipment: ["dumbbells", "kettlebells"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 75, notes: "Wide stance, toes out, weight between legs" },
  { id: "legs_lunge", name: "Walking Lunge", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Long stride, front knee over ankle" },
  { id: "legs_reverse_lunge", name: "Reverse Lunge", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Step back, lower back knee toward floor" },
  { id: "legs_curtsy_lunge", name: "Curtsy Lunge", category: "Legs", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Adductors"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Cross back leg behind and to the outside" },
  { id: "legs_lateral_lunge", name: "Lateral Lunge", category: "Legs", muscleGroup: "Inner Thighs", primaryMuscle: "Adductors", secondaryMuscles: ["Quads", "Glutes"], equipment: ["none"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 60, notes: "Step wide to the side, sit back into hip" },
  { id: "legs_rdl", name: "Romanian Deadlift (DB)", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Lower Back"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 90, notes: "Hinge at hips, feel hamstring stretch" },
  { id: "legs_single_leg_rdl", name: "Single-Leg RDL", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Core"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8/leg", restSeconds: 75, notes: "Hinge on one leg, back leg extends behind" },
  { id: "legs_nordics", name: "Nordic Curl", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: [], equipment: ["bench"], difficulty: "advanced", type: "isolation", sets: 3, reps: "5-8", restSeconds: 90, notes: "Feet anchored, lower slowly using hamstrings" },
  { id: "legs_leg_curl", name: "Leg Curl", category: "Legs", muscleGroup: "Hamstrings", primaryMuscle: "Hamstrings", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Controlled negative, full range of motion" },
  { id: "legs_leg_ext", name: "Leg Extension", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Squeeze quad at top, control the descent" },
  { id: "legs_calf", name: "Calf Raise", category: "Legs", muscleGroup: "Calves", primaryMuscle: "Gastrocnemius", secondaryMuscles: ["Soleus"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 4, reps: "15-20", restSeconds: 45, notes: "Full range, pause at top" },
  { id: "legs_seated_calf", name: "Seated Calf Raise", category: "Legs", muscleGroup: "Calves", primaryMuscle: "Soleus", secondaryMuscles: ["Gastrocnemius"], equipment: ["dumbbells", "bench"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Seated position isolates the soleus" },
  { id: "legs_leg_press", name: "Leg Press", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["cable_machine"], difficulty: "beginner", type: "compound", sets: 4, reps: "10-15", restSeconds: 90, notes: "Feet shoulder-width, don't lock out knees" },
  { id: "legs_hack_squat", name: "Hack Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["cable_machine"], difficulty: "intermediate", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Low bar position on shoulders, deep squat" },
  { id: "legs_step_up", name: "Step-Up", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["box", "bench"], difficulty: "beginner", type: "compound", sets: 3, reps: "10/leg", restSeconds: 60, notes: "Drive through heel, controlled descent" },
  { id: "legs_sissy_squat", name: "Sissy Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: [], equipment: ["none"], difficulty: "advanced", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lean back, knees forward over toes" },
  { id: "legs_split_squat", name: "Bulgarian Split Squat", category: "Legs", muscleGroup: "Quads/Glutes", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10/leg", restSeconds: 90, notes: "Rear foot on bench, drive through front heel" },
  { id: "legs_wall_sit", name: "Wall Sit", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "30-60s", restSeconds: 60, notes: "Back flat against wall, knees at 90°, hold" },
  { id: "legs_box_jump", name: "Box Jump", category: "Legs", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["box"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-10", restSeconds: 75, notes: "Explosive jump, land softly, step back down" },
  { id: "legs_pistol_squat", name: "Pistol Squat", category: "Legs", muscleGroup: "Quads", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Core"], equipment: ["none"], difficulty: "advanced", type: "compound", sets: 3, reps: "3-6/leg", restSeconds: 90, notes: "Single-leg squat, opposite leg extended forward" },
  { id: "legs_db_lunge_walking", name: "DB Walking Lunge", category: "Legs", muscleGroup: "Quads/Glutes", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Hold DBs at sides, long controlled strides" },

  // ═══════════════════════════════════════════════════════════════════════════
  // SHOULDERS (~18 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "sh_lateral", name: "Lateral Raise", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Slight bend in elbows, lead with elbows" },
  { id: "sh_cable_lateral", name: "Cable Lateral Raise", category: "Shoulders", muscleGroup: "Lateral Delts", primaryMuscle: "Lateral Delts", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Constant tension throughout the range" },
  { id: "sh_ohp_db", name: "DB Overhead Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps", "Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Core tight, press straight overhead" },
  { id: "sh_ohp_bb", name: "Barbell OHP", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps", "Traps"], equipment: ["barbell", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "6-10", restSeconds: 120, notes: "Bar starts at upper chest, press overhead" },
  { id: "sh_arnold_press", name: "Arnold Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Lateral Delts", "Triceps"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 90, notes: "Rotate palms out as you press — hits all three delt heads" },
  { id: "sh_front_raise", name: "Front Raise", category: "Shoulders", muscleGroup: "Front Delts", primaryMuscle: "Front Delts", secondaryMuscles: [], equipment: ["dumbbells", "barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Controlled movement, don't swing" },
  { id: "sh_face_pull", name: "Face Pull", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rotator Cuff", "Traps"], equipment: ["cable_machine", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Pull to forehead level, external rotation" },
  { id: "sh_reverse_fly", name: "Reverse Fly", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rhomboids", "Traps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Hinge forward, fly out to the sides" },
  { id: "sh_upright_row", name: "Upright Row", category: "Shoulders", muscleGroup: "Shoulders/Traps", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Traps", "Biceps"], equipment: ["barbell", "dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Bar close to body, lead with elbows up to chin level" },
  { id: "sh_shrug", name: "Barbell Shrug", category: "Shoulders", muscleGroup: "Traps", primaryMuscle: "Traps", secondaryMuscles: [], equipment: ["barbell", "dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Shrug straight up, hold at top for 1s" },
  { id: "sh_band_pull_apart", name: "Band Pull-Apart", category: "Shoulders", muscleGroup: "Rear Delts", primaryMuscle: "Rear Delts", secondaryMuscles: ["Rhomboids"], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20-25", restSeconds: 45, notes: "Arms straight, pull band apart to chest width" },
  { id: "sh_pike_pushup", name: "Pike Push-Up", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Triceps"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 75, notes: "Hips high in pike position, lower head toward floor" },
  { id: "sh_handstand_pushup", name: "Handstand Push-Up (wall)", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Triceps", "Traps"], equipment: ["none"], difficulty: "advanced", type: "compound", sets: 3, reps: "3-8", restSeconds: 120, notes: "Kick up against wall, lower head to floor and press" },
  { id: "sh_db_shrug", name: "Dumbbell Shrug", category: "Shoulders", muscleGroup: "Traps", primaryMuscle: "Traps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 60, notes: "Shrug and hold, don't roll shoulders" },
  { id: "sh_lu_raise", name: "Lu Raise", category: "Shoulders", muscleGroup: "Lateral Delts", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Front Delts"], equipment: ["dumbbells"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Thumbs-up lateral raise with slight forward lean" },
  { id: "sh_behind_neck_press", name: "Behind-the-Neck Press (Smith)", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Lateral Delts", secondaryMuscles: ["Front Delts", "Traps"], equipment: ["smith_machine"], difficulty: "advanced", type: "compound", sets: 3, reps: "8-10", restSeconds: 90, notes: "Use light weight, good shoulder mobility required" },
  { id: "sh_push_press", name: "Push Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Triceps", "Quads"], equipment: ["barbell", "squat_rack"], difficulty: "intermediate", type: "compound", sets: 4, reps: "5-8", restSeconds: 120, notes: "Slight knee dip for momentum, press overhead explosively" },
  { id: "sh_z_press", name: "Z-Press", category: "Shoulders", muscleGroup: "Shoulders", primaryMuscle: "Front Delts", secondaryMuscles: ["Core", "Triceps"], equipment: ["dumbbells", "barbell"], difficulty: "advanced", type: "compound", sets: 3, reps: "8-10", restSeconds: 90, notes: "Seated on floor with legs extended, no back support" },

  // ═══════════════════════════════════════════════════════════════════════════
  // ARMS (~22 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "arm_curl_db", name: "Dumbbell Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Supinate at top, control the descent" },
  { id: "arm_curl_bb", name: "Barbell Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: ["Brachialis"], equipment: ["barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Full range, don't cheat with momentum" },
  { id: "arm_hammer_curl", name: "Hammer Curl", category: "Arms", muscleGroup: "Biceps/Brachialis", primaryMuscle: "Brachialis", secondaryMuscles: ["Biceps", "Brachioradialis"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Neutral grip, controlled movement" },
  { id: "arm_incline_curl", name: "Incline DB Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps Long Head", secondaryMuscles: ["Brachialis"], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Incline bench stretches bicep at bottom for full ROM" },
  { id: "arm_conc_curl", name: "Concentration Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Elbow on inner knee, strict curl for peak contraction" },
  { id: "arm_cable_curl", name: "Cable Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Constant tension, don't let elbows flare" },
  { id: "arm_preacher_curl", name: "Preacher Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps Short Head", secondaryMuscles: [], equipment: ["barbell", "cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Arm on pad, full stretch at bottom" },
  { id: "arm_reverse_curl", name: "Reverse Curl", category: "Arms", muscleGroup: "Forearms", primaryMuscle: "Brachioradialis", secondaryMuscles: ["Biceps"], equipment: ["barbell", "dumbbells"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Overhand grip, works brachioradialis and forearms" },
  { id: "arm_spider_curl", name: "Spider Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps Short Head", secondaryMuscles: [], equipment: ["dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Chest on incline bench, arms hang straight, curl up" },
  { id: "arm_21s", name: "21s (Bicep Curl)", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Biceps", secondaryMuscles: [], equipment: ["barbell", "dumbbells"], difficulty: "intermediate", type: "isolation", sets: 2, reps: "21 total", restSeconds: 90, notes: "7 bottom half, 7 top half, 7 full reps — brutal pump" },
  { id: "arm_tricep_ext", name: "Overhead Tricep Extension", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12", restSeconds: 60, notes: "Keep elbows tucked, extend fully" },
  { id: "arm_tricep_pushdown", name: "Cable Pushdown", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Lateral Head", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Elbows fixed to sides, full extension" },
  { id: "arm_dips", name: "Tricep Dips", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Front Delts", "Chest"], equipment: ["dip_bars", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lean slightly forward, elbows behind you" },
  { id: "arm_skull_crusher", name: "Skull Crusher", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["barbell", "dumbbells", "bench"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Lower bar to forehead, keep elbows fixed" },
  { id: "arm_close_grip_press", name: "Close-Grip Bench Press", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], equipment: ["barbell", "bench"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-12", restSeconds: 90, notes: "Shoulder-width grip, elbows tucked in" },
  { id: "arm_overhead_cable_ext", name: "Overhead Cable Extension", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps Long Head", secondaryMuscles: [], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Face away from cable, extend arms overhead" },
  { id: "arm_diamond_pushup", name: "Diamond Push-Up", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], equipment: ["none"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8-15", restSeconds: 60, notes: "Diamond hand position, elbows flare out slightly" },
  { id: "arm_kickback", name: "Tricep Kickback", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: [], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Upper arm parallel to floor, extend fully at back" },
  { id: "arm_bench_dip", name: "Bench Dip", category: "Arms", muscleGroup: "Triceps", primaryMuscle: "Triceps", secondaryMuscles: ["Front Delts"], equipment: ["bench"], difficulty: "beginner", type: "compound", sets: 3, reps: "12-15", restSeconds: 60, notes: "Hands on bench behind you, lower and press up" },
  { id: "arm_wrist_curl", name: "Wrist Curl", category: "Arms", muscleGroup: "Forearms", primaryMuscle: "Forearm Flexors", secondaryMuscles: [], equipment: ["dumbbells", "barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Forearms on thighs, curl wrists up" },
  { id: "arm_reverse_wrist_curl", name: "Reverse Wrist Curl", category: "Arms", muscleGroup: "Forearms", primaryMuscle: "Forearm Extensors", secondaryMuscles: [], equipment: ["dumbbells", "barbell"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Overhand grip, extend wrists up" },
  { id: "arm_cross_body_curl", name: "Cross-Body Hammer Curl", category: "Arms", muscleGroup: "Biceps", primaryMuscle: "Brachialis", secondaryMuscles: ["Biceps"], equipment: ["dumbbells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10-12/arm", restSeconds: 60, notes: "Curl DB across body toward opposite shoulder" },

  // ═══════════════════════════════════════════════════════════════════════════
  // CORE (~22 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "core_plank", name: "Plank", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abs", secondaryMuscles: ["Rectus Abs", "Obliques"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "30-60s", restSeconds: 45, notes: "Straight line from head to heels, no sagging" },
  { id: "core_side_plank", name: "Side Plank", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Transverse Abs"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "30s/side", restSeconds: 30, notes: "Stack feet, hips high, don't let hips sag" },
  { id: "core_crunch", name: "Crunch", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Lift shoulders off floor, squeeze at top" },
  { id: "core_bicycle", name: "Bicycle Crunch", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Rectus Abs"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/side", restSeconds: 45, notes: "Opposite elbow to knee, slow and controlled" },
  { id: "core_mountain", name: "Mountain Climbers", category: "Core", muscleGroup: "Core", primaryMuscle: "Core", secondaryMuscles: ["Hip Flexors", "Shoulders"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "20/side", restSeconds: 45, notes: "Quick alternating knees to chest, plank position" },
  { id: "core_leg_raise", name: "Hanging Leg Raise", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["pull_up_bar"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10-15", restSeconds: 60, notes: "Don't swing, lift legs with abs" },
  { id: "core_lying_leg_raise", name: "Lying Leg Raise", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "12-15", restSeconds: 45, notes: "Lower back pressed into floor, lift legs to 90°" },
  { id: "core_flutter_kick", name: "Flutter Kicks", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20/side", restSeconds: 45, notes: "Small rapid kicks, feet 6 inches off floor" },
  { id: "core_dead_bug", name: "Dead Bug", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abs", secondaryMuscles: ["Rectus Abs"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10/side", restSeconds: 45, notes: "Opposite arm/leg extend, lower back stays flat" },
  { id: "core_bird_dog", name: "Bird Dog", category: "Core", muscleGroup: "Core", primaryMuscle: "Erector Spinae", secondaryMuscles: ["Glutes", "Transverse Abs"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "10/side", restSeconds: 45, notes: "On all fours, extend opposite arm and leg, hold 2s" },
  { id: "core_v_up", name: "V-Up", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15", restSeconds: 60, notes: "Arms and legs rise simultaneously to form V shape" },
  { id: "core_hollow_hold", name: "Hollow Body Hold", category: "Core", muscleGroup: "Core", primaryMuscle: "Rectus Abs", secondaryMuscles: ["Transverse Abs"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "20-30s", restSeconds: 45, notes: "Arms overhead, legs extended, lower back pressed down" },
  { id: "core_russian_twist", name: "Russian Twist", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Rectus Abs"], equipment: ["none", "dumbbells", "kettlebells"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/side", restSeconds: 45, notes: "Lean back, feet off floor, rotate side to side" },
  { id: "core_ab_wheel", name: "Ab Wheel Rollout", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: ["Lats", "Triceps"], equipment: ["ab_wheel"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "8-12", restSeconds: 75, notes: "Knees on floor, roll out slow, squeeze abs to return" },
  { id: "core_pallof_press", name: "Pallof Press", category: "Core", muscleGroup: "Anti-Rotation", primaryMuscle: "Obliques", secondaryMuscles: ["Transverse Abs"], equipment: ["cable_machine", "resistance_bands"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10/side", restSeconds: 60, notes: "Press away from cable, resist rotation" },
  { id: "core_dragon_flag", name: "Dragon Flag", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["bench"], difficulty: "advanced", type: "isolation", sets: 3, reps: "5-8", restSeconds: 90, notes: "Shoulders anchored, lower entire body as one unit" },
  { id: "core_woodchop", name: "Cable Woodchop", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: ["Transverse Abs", "Shoulders"], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12/side", restSeconds: 60, notes: "Rotate from hip, diagonal chop motion" },
  { id: "core_toe_touch", name: "Toe Touch", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Legs vertical, reach hands to toes with crunch" },
  { id: "core_situp", name: "Sit-Up", category: "Core", muscleGroup: "Abs", primaryMuscle: "Rectus Abs", secondaryMuscles: ["Hip Flexors"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Controlled up and down, don't yank on neck" },
  { id: "core_heel_tap", name: "Heel Tap", category: "Core", muscleGroup: "Obliques", primaryMuscle: "Obliques", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20/side", restSeconds: 45, notes: "Shoulders off floor, reach each hand to same-side heel" },
  { id: "core_reverse_crunch", name: "Reverse Crunch", category: "Core", muscleGroup: "Lower Abs", primaryMuscle: "Lower Abs", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Curl hips up toward chest, control the return" },
  { id: "core_plank_shoulder_tap", name: "Plank Shoulder Tap", category: "Core", muscleGroup: "Core", primaryMuscle: "Transverse Abs", secondaryMuscles: ["Obliques", "Shoulders"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10/side", restSeconds: 45, notes: "High plank, tap opposite shoulder, minimize hip rotation" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GLUTES (~16 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "glute_bridge", name: "Glute Bridge", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Squeeze glutes at top, hold 1-2 seconds" },
  { id: "glute_hip_thrust_bw", name: "Hip Thrust (Bodyweight)", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], equipment: ["bench"], difficulty: "beginner", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Upper back on bench, drive hips up, squeeze at top" },
  { id: "glute_hip_thrust_bb", name: "Barbell Hip Thrust", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], equipment: ["barbell", "bench"], difficulty: "intermediate", type: "compound", sets: 4, reps: "8-12", restSeconds: 90, notes: "Bar across hips, drive through heels, full hip extension" },
  { id: "glute_single_bridge", name: "Single-Leg Glute Bridge", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], equipment: ["none"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "10/leg", restSeconds: 60, notes: "One leg raised, drive hips up with working leg" },
  { id: "glute_kickback", name: "Donkey Kick", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "On all fours, kick one leg back and up" },
  { id: "glute_fire_hydrant", name: "Fire Hydrant", category: "Glutes", muscleGroup: "Glutes/Abductors", primaryMuscle: "Glute Medius", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "On all fours, lift knee to side at 90°" },
  { id: "glute_clamshell", name: "Clamshell", category: "Glutes", muscleGroup: "Glute Medius", primaryMuscle: "Glute Medius", secondaryMuscles: [], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/side", restSeconds: 45, notes: "Side-lying, heels together, open knees like clamshell" },
  { id: "glute_band_walk", name: "Banded Lateral Walk", category: "Glutes", muscleGroup: "Glute Medius", primaryMuscle: "Glute Medius", secondaryMuscles: ["Glutes"], equipment: ["resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/direction", restSeconds: 45, notes: "Band above knees, sidestep with tension, stay low" },
  { id: "glute_sumo_deadlift", name: "Sumo Deadlift (DB)", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Quads"], equipment: ["dumbbells", "kettlebells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10-12", restSeconds: 75, notes: "Wide stance, DB hangs between legs, drive hips" },
  { id: "glute_cable_kickback", name: "Cable Glute Kickback", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], equipment: ["cable_machine"], difficulty: "intermediate", type: "isolation", sets: 3, reps: "12-15/leg", restSeconds: 60, notes: "Ankle strap, kick back with straight leg, squeeze glute" },
  { id: "glute_frog_pump", name: "Frog Pump", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: [], equipment: ["none"], difficulty: "beginner", type: "isolation", sets: 3, reps: "20-30", restSeconds: 45, notes: "Feet together, knees out, pump hips up like a frog" },
  { id: "glute_kb_swing", name: "Kettlebell Swing (Glute)", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], equipment: ["kettlebells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "15-20", restSeconds: 60, notes: "Explosive hip snap drives the bell, squeeze glutes hard" },
  { id: "glute_curtsy_lunge_g", name: "Weighted Curtsy Lunge", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Adductors"], equipment: ["dumbbells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "10/leg", restSeconds: 75, notes: "Step back and across, hold DBs at sides" },
  { id: "glute_rdl_single", name: "Single-Leg RDL (Glute focus)", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], equipment: ["dumbbells", "kettlebells"], difficulty: "intermediate", type: "compound", sets: 3, reps: "8/leg", restSeconds: 75, notes: "Hinge on one leg, focus on squeezing glute at top" },
  { id: "glute_abduction", name: "Machine Hip Abduction", category: "Glutes", muscleGroup: "Glute Medius", primaryMuscle: "Glute Medius", secondaryMuscles: ["Glutes"], equipment: ["cable_machine"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15-20", restSeconds: 45, notes: "Push knees outward against pads, squeeze at end" },
  { id: "glute_standing_kickback", name: "Standing Glute Kickback", category: "Glutes", muscleGroup: "Glutes", primaryMuscle: "Glutes", secondaryMuscles: [], equipment: ["none", "resistance_bands"], difficulty: "beginner", type: "isolation", sets: 3, reps: "15/leg", restSeconds: 45, notes: "Stand on one leg, kick other leg back, squeeze glute" },

  // ═══════════════════════════════════════════════════════════════════════════
  // CARDIO (~18 exercises)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "cardio_run", name: "Treadmill Run", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Quads", secondaryMuscles: ["Calves", "Glutes", "Hamstrings"], equipment: ["treadmill"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "Moderate pace, 65-75% max HR" },
  { id: "cardio_walk_incline", name: "Incline Treadmill Walk", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Glutes", secondaryMuscles: ["Calves", "Hamstrings"], equipment: ["treadmill"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "12-15% incline, 3-4 mph, great for fat burn" },
  { id: "cardio_hiit_run", name: "HIIT Sprint Intervals", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Quads", secondaryMuscles: ["Calves", "Glutes"], equipment: ["treadmill"], difficulty: "advanced", type: "cardio", sets: 8, reps: "30s sprint / 30s rest", restSeconds: 30, notes: "All-out sprint followed by walk recovery" },
  { id: "cardio_cycle", name: "Stationary Bike", category: "Cardio", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Calves", "Hamstrings"], equipment: ["cycle"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "Moderate resistance, steady cadence 70-90 RPM" },
  { id: "cardio_jump_rope", name: "Jump Rope", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Calves", secondaryMuscles: ["Shoulders", "Core"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "2-3 min", restSeconds: 60, notes: "Light bounce on balls of feet, wrists drive the rope" },
  { id: "cardio_burpee", name: "Burpees", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: ["Chest", "Quads", "Core"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "10-15", restSeconds: 60, notes: "Drop, push-up, jump — no rest between reps" },
  { id: "cardio_rowing", name: "Rowing Machine", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Lats", secondaryMuscles: ["Quads", "Biceps", "Core"], equipment: ["cable_machine"], difficulty: "beginner", type: "cardio", sets: 1, reps: "15-20 min", restSeconds: 0, notes: "Drive with legs first, then lean back, then pull arms" },
  { id: "cardio_battle_ropes", name: "Battle Ropes", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Core", "Arms"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 4, reps: "30s on / 30s off", restSeconds: 30, notes: "Alternate waves, slam waves, or double waves" },
  { id: "cardio_stair", name: "Stair Climber", category: "Cardio", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Calves"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 1, reps: "15-20 min", restSeconds: 0, notes: "Upright posture, don't lean on handrails" },
  { id: "cardio_high_knees", name: "High Knees", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Hip Flexors", secondaryMuscles: ["Quads", "Core"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "30s", restSeconds: 30, notes: "Drive knees to chest height rapidly" },
  { id: "cardio_jumping_jack", name: "Jumping Jacks", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: ["Shoulders", "Calves"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "30-60s", restSeconds: 30, notes: "Jump feet wide and clap overhead, repeat" },
  { id: "cardio_bear_crawl", name: "Bear Crawl", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Core", secondaryMuscles: ["Shoulders", "Quads"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "30s", restSeconds: 45, notes: "On all fours, knees off floor, crawl forward and back" },
  { id: "cardio_tabata", name: "Tabata (any exercise)", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Full Body", secondaryMuscles: [], equipment: ["none"], difficulty: "advanced", type: "cardio", sets: 8, reps: "20s work / 10s rest", restSeconds: 10, notes: "4 minutes total, max effort each 20s interval" },
  { id: "cardio_shadow_boxing", name: "Shadow Boxing", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Shoulders", secondaryMuscles: ["Core", "Arms"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 3, reps: "3 min rounds", restSeconds: 60, notes: "Light on feet, jab-cross combos, engage core" },
  { id: "cardio_outdoor_run", name: "Outdoor Run", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Quads", secondaryMuscles: ["Calves", "Hamstrings", "Glutes"], equipment: ["none"], difficulty: "beginner", type: "cardio", sets: 1, reps: "20-45 min", restSeconds: 0, notes: "Conversational pace for endurance, or intervals for HIIT" },
  { id: "cardio_swimming", name: "Swimming", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Lats", secondaryMuscles: ["Shoulders", "Core", "Legs"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 1, reps: "20-30 min", restSeconds: 0, notes: "Low impact, full body engagement — excellent for recovery" },
  { id: "cardio_cycling_outdoor", name: "Outdoor Cycling", category: "Cardio", muscleGroup: "Legs", primaryMuscle: "Quads", secondaryMuscles: ["Glutes", "Hamstrings", "Calves"], equipment: ["cycle"], difficulty: "beginner", type: "cardio", sets: 1, reps: "30-60 min", restSeconds: 0, notes: "Steady cadence, mix flat and hill intervals" },
  { id: "cardio_skaters", name: "Skater Jumps", category: "Cardio", muscleGroup: "Full Body", primaryMuscle: "Glutes", secondaryMuscles: ["Quads", "Core"], equipment: ["none"], difficulty: "intermediate", type: "cardio", sets: 3, reps: "10/side", restSeconds: 45, notes: "Lateral jump from one leg to the other, like skating" },
];

export function getExercisesByCategory(cat: string): ExerciseEntry[] {
  return allExercises.filter((e) => e.category === cat);
}

export function searchExercises(q: string, cat?: string): ExerciseEntry[] {
  const lower = q.toLowerCase();
  return allExercises.filter((e) => {
    const match = !q || e.name.toLowerCase().includes(lower) || e.muscleGroup.toLowerCase().includes(lower) || e.primaryMuscle.toLowerCase().includes(lower);
    const catMatch = !cat || e.category === cat;
    return match && catMatch;
  });
}

export function filterByEquipment(exercises: ExerciseEntry[], equipment: EquipmentType[]): ExerciseEntry[] {
  if (!equipment.length) return exercises;
  const set = new Set(equipment);
  set.add("none");
  return exercises.filter((e) => e.equipment.some((eq) => set.has(eq)));
}

export function filterByDifficulty(exercises: ExerciseEntry[], difficulty: Difficulty): ExerciseEntry[] {
  return exercises.filter((e) => e.difficulty === difficulty);
}
